name: Cancel Stale Runs

on: [pull_request_target]

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: build-wheels.yml
          access_token: ${{ github.token }}
