name: Run Tests

on: [push, pull_request]

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2016, macOS-10.15]
        python: ['3.6', '3.7']

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: python -m pip install -r requirements.txt -r requirements-test.txt

      - name: Build pickle5
        run: |
          python -m pip install setuptools wheel
          python -m pip install .

      - name: Run tests
        working-directory: ..  # avoid picking up source tree
        run: |
          python -m pickle5.test.test_picklebuffer -v
          python -m pickle5.test.test_pickle
